name: Daily AI Trends Analysis

on:
  schedule:
    # 한국시간 오전 9시 = UTC 00:00, 월-금요일만 실행
    - cron: "0 0 * * 1-5"

  # 수동 실행 가능
  workflow_dispatch:
    inputs:
      test_mode:
        description: "Run in test mode (no email)"
        required: false
        type: boolean
        default: false

jobs:
  analyze-trends:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AI Trends Analysis
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          TEST_MODE: ${{ github.event.inputs.test_mode }}
        run: |
          python main.py
